Hw02 express
Olena-Zhyzhko/nodejs-homework-rest-api pull request #1
Opened 2022-12-11 10:07 UTC by Olena-Zhyzhko

Перевірте будь ласка

2022-12-11 19:46 UTC, BohdanGres requested changes
Привіт, все добре пропоную винести валідацю в мідлварку + додати мадлвар для ваідації req.params

2022-12-12 10:57 UTC, Olena-Zhyzhko commented
Додадала два meddleware: один на валідацію реквест боді, другий на валідацію реквест парамс.

2022-12-12 17:34 UTC, BohdanGres requested changes
трошки треба переробити

2022-12-12 17:34 UTC, BohdanGres commented on meddlewares/validateParams.js
> +        const { error } = schema.validate(req.params.contactId);
тут треба передавати саме req.params бо інакше виходить що використати з якоюсь іншою структурою данних вже не вийде цю мідлварку

2022-12-12 18:23 UTC, Olena-Zhyzhko commented
Виправлено

2022-12-13 07:53 UTC, BohdanGres approved these changes

2022-12-13 10:41 UTC, merged