hw3 is do
Olena-Zhyzhko/nodejs-homework-rest-api pull request #2
Opened 2022-12-15 10:59 UTC by Olena-Zhyzhko

Перевірте будь ласка

2022-12-15 20:11 UTC, BohdanGres requested changes

2022-12-15 20:11 UTC, BohdanGres commented on server.js
> +    app.listen(PORT);
сюди додай колбек з повідомленням що сервак стартанув, інашке не відомо коли він готов оброляти запити

2022-12-15 20:11 UTC, BohdanGres commented on meddlewares/validateBody.js
> +
тут шось накрутила сильно, якщо треба що б в деяких випадках всі параметри були обов`язкові а в деяких ні то ліпше просто створити 2 схеми Joi де описати так як треба і передавати сюди під різні ендпоінти

2022-12-15 20:11 UTC, BohdanGres commented on controllers/contacts/updateStatusContact.js
> +    if (!result) {
файл вище такий самий як і цей, різниця між PUT і PATCH в тому що при путі ми повністю перезаписуємо весь об`єкт окрім id а от в патчі мона міняти тільки якісь поля. В твоїй реалізації виходить ти можеш залиги один контролер але в мідлвар давати різні схеми для валідації. Для пут - усі поля обов`язкові, для патч усі не обов`язкові але треба глянути що хоч щось відправили

2022-12-18 09:55 UTC, Olena-Zhyzhko commented on controllers/contacts/updateStatusContact.js
> +    if (!result) {
один контролер використано на два роута, відрізняються схемами перевірки джой

2022-12-18 09:56 UTC, Olena-Zhyzhko commented on meddlewares/validateBody.js
> +
мидлвар використовується для двох роутів, за різними схемами джой

2022-12-18 09:56 UTC, Olena-Zhyzhko commented on server.js
> +    app.listen(PORT);
Колбек додано

2022-12-18 13:33 UTC, BohdanGres approved these changes

2022-12-19 08:25 UTC, merged