04 auth
Olena-Zhyzhko/nodejs-homework-rest-api pull request #3
Opened 2023-01-04 21:30 UTC by Olena-Zhyzhko

Перевірте будь ласка.

2023-01-05 17:13 UTC, BohdanGres requested changes
все добре декілька дрібниць

2023-01-05 17:13 UTC, BohdanGres commented on meddlewares/authenticate.js
> +        if (!user || !user.token) {
забули перевірити user.token === token

2023-01-05 17:13 UTC, BohdanGres commented on app.js
>  app.use('/api/contacts', contactsRouter)
спробуй навісити авторизаційний мідлвар ось тут одразу на всі contacts, але перевір чи помилки нормально обробляються

2023-01-08 17:37 UTC, Olena-Zhyzhko commented on meddlewares/authenticate.js
> +        if (!user || !user.token) {
додано

2023-01-08 17:37 UTC, Olena-Zhyzhko commented on app.js
>  app.use('/api/contacts', contactsRouter)
зроблено

2023-01-09 09:07 UTC, BohdanGres approved these changes

2023-01-09 20:22 UTC, merged